# git-cliff release notes configuration
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "usepictum"
repo = "pictum-web"

[bump]
features_always_bump_minor = false
initial_tag = "0.1.0"

[changelog]
header = """
## Release notes\n
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group }}
  {% for commit in commits %}
    {% if commit.remote.pr_title -%}
      {%- set commit_message = commit.remote.pr_title -%}
    {%- else -%}
      {%- set commit_message = commit.message -%}
    {%- endif -%}
    * {{ commit_message | split(pat="\n") | first | trim }}\
      {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
      {% if commit.remote.pr_number %} in \
        [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
      {%- endif -%}
      {{ " " }}([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
  {%- endfor %}

{% endfor -%}

{%- if github -%}
{% if github.contributors | length != 0 %}
  {% raw %}\n{% endraw -%}
  ### Contributors
{%- endif %}\
{% for contributor in github.contributors %}
  * [@{{ contributor.username }}]({{ self::github_user_url(username=contributor.username) }})
{%- endfor -%}
{%- endif -%}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro github_user_url(username) -%}
  {%- if username is ending_with("[bot]") -%}
    https://github.com/apps/{{ username | replace(from="[bot]", to="") }}
  {%- else -%}
    https://github.com/{{ username }}
  {%- endif -%}
{%- endmacro -%}
"""
trim = true
footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance Improvements" },
  { message = "^revert", group = "Reverts" },
]
split_commits = false
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
filter_commits = true
topo_order = false
sort_commits = "newest"
