name: Quality

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Set up Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1

      - name: Check formatting and lint rules
        run: biome ci
